version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: maintenance-mysql
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: maintenance_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend
    container_name: maintenance-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    command: node src/app.js